<?
    $item = Mikron_Entity::$item;
    $class_name = $item->class_name;
    $fields = $class_name::getFields();
    $id = Mikron_Crud::getNextId();
    $_css_class = 'btn btn-simple';
?>

<a href="#" class="<?=$_css_class?>" onclick="return CustomUI.showForm('form-add_<?=$id?>');" >Создать</a>

<form action="/add" method="post" class="form-horizontal popup-ajax popup-form" id="form-add_<?=$id?>" title="Создать">
    <div class="popup-form-content">
        <?$class_name::drawAddForm(new Params(array('hide_footer' => true)))?>
        <?foreach($fields as $field_name => $field){?>
            <?$_input_id = 'input_'.$field_name.'_'.Mikron_Crud::getNextId()?>
            <div class="control-group">
                <label class="control-label" for="<?=$_input_id?>"><?=$field->description?>:</label>
                <div class="controls">
                    <input type="email" name="form[<?=$field_name?>]" class="form-control" id="<?=$_input_id?>" placeholder="" />
                </div>
            </div>
        <?}?>
    </div>
    <div class="popup-form-footer">
        <a class="btn btn-primary" href="#" onclick="$(this).closest('form').submit(); return false;">Создать</a>
        <a href="#" onclick="return CustomUI.hideForm();" style="margin-left: 1em;">Отмена</a>
    </div>
</form>
