
		<div class="wg-govprogs-lg" data-ix="govprog-hiddden">
			<div class="w-clearfix govprogs-nav-bar-lg">
				<div class="govprogs-set-btn-lg" data-ix="govprogs-settings-show"></div>
				<div class="govprogs-compare-btn-lg"></div>
			</div>
			<h4 class="invert">Расходы <a class="wg-h4-link invertlink" href="#">бюджета</a> Минпром-торга по
				<a class="wg-h4-link invertlink" href="#">госпрограммам</a><br>в 2015 году
			</h4>
			<h3 class="one-year center"><span class="big">231,51</span><br>млрд. Р</h3>
			<div class="govprogs-more-btn-lg"><a class="govprogs-more-link-lg black" href="#" data-ix="govprogs-show-details">Из чего состоит сумма</a>
			</div>
		</div>

		<div class="w-clearfix wg-govprogs-expand-lg">
			<div class="govprogs-expand-popups">
				<div class="govprogs-timeline-2013" data-ix="dynamics-hidden">
					<div class="whitetext yeardynamics">Общий расход по всем
						<br>госпрограммам в 2014 году</div>
					<h3 class="yeardynamics-h3">205 млрд. руб.</h3>
				</div>
				<div class="govprogs-timeline-2014" data-ix="dynamics-hidden">
					<div class="whitetext yeardynamics">Общий расход по всем
						<br>госпрограммам в 2014 году</div>
					<h3 class="yeardynamics-h3">198 млрд. руб.</h3>
				</div>
				<div class="govprogs-timeline-2015" data-ix="dynamics-hidden">
					<div class="whitetext yeardynamics">Общий расход по всем
						<br>госпрограммам в 2015 году</div>
					<h3 class="yeardynamics-h3">231,51 млрд. руб.</h3>
				</div>
				<div class="ed-tips">
					<div class="w-clearfix ed-govprog">
						<div class="ed-govprog-close-btn" data-ix="close-ed-govprog"></div>
						<h3 class="popup-h3">Что такое госспрограмма</h3>
						<p class="whitetext">Система мероприятий и инструментов государственной политики, обеспечивающих
						в рамках реализации ключевых государственных функций достижение приоритетов и целей государственной политики
						в сфере социально-экономического развития и безопасности.</p>
						<a class="popup-link" href="#">Словарь</a>
						<a class="popup-link" href="#">Нормативная база</a>
						<a class="popup-link" href="#">Обучающий раздел</a>
					</div>
				</div>
				<div class="govprogs-v-3-pop" data-ix="v-pop-hidden">
					<h3 class="yeardynamics-h3 v-bar">13,09 млрд. руб.</h3>
					<div class="whitetext yeardynamics v-bar">Развитие фармацевтической и мед. промышленности на 2013 — 2020 годы</div>
				</div>
			</div>
			<div class="w-clearfix govprogs-nav-bar-lg">
				<div class="govprogs-set-btn-lg" data-ix="govprogs-settings-show"></div>
				<div class="govprogs-compare-btn-lg"></div>
			</div>
			<div class="expand-left-collumn">
				<h4>Расходы бюджета Минпром-торга РФ по <a class="wg-h4-link" data-ix="ed-govprog-show" href="#" style="">госпрограммам</a><br>в 2015 году</h4>
				<h3 class="one-year">231,51 млрд. Р</h3>
				<div class="govprogs-years-compare"></div>
				<div class="govprogs-year-dot-2013" data-ix="show-dym-2013"></div>
				<div class="govprogs-year-dot-2014" data-ix="show-dym-2014"></div>
				<div class="govsprogs-year-dot-2015" data-ix="show-dym-2015"></div>
				<div class="govprogs-hide-more-btn-lg">
					<a class="govprogs-more-link-lg black" href="#" data-ix="govprogs-hide-details">Свернуть подробности</a>
				</div>
			</div>
			<div class="w-clearfix expand-right-collumn">
				<div class="govprogs-2015-unit-select-num"><a class="govprogs-2015-unit-link-num" href="#">млрд. руб.&nbsp;<span class="triangle-sign">▼</span></a>
				</div>
				<h4 class="black-h4">Расходы бюджета за&nbsp;<a class="wg-h4-link invertlink" href="#">2015</a>&nbsp;год по госпрограммам состоят из:</h4>
				<div class="w-clearfix govprogs-expand-v-bar-2015">
					<div class="govprogs-2015-v-1"><a class="v-1-link" href="#">130,8</a>
					</div>
					<div class="govprogs-2015-v-2"><a class="v-2-link" href="#">62,08</a>
					</div>
					<div class="govprogs-2015-v-3" data-ix="govprogs-v-3-show-hint"><a class="v-3-link" href="#">13,09</a>
					</div>
					<div class="govprogs-2015-v-4"><a class="v-4-link" href="#">12,49</a>
					</div>
					<div class="govprogs-2015-v-5"><a class="v-5-link" href="#">9,1</a>
					</div>
					<div class="govprogs-2015-v-6"><a class="v-6-link" href="#">1,49</a>
					</div>
					<div class="govprogs-2015-v-7"><a class="v-7-link" href="#">0,9</a>
					</div>
					<div class="govpogs-2015-v-8"><a class="v-8-link" href="#">0,69</a>
					</div>
					<div class="govprogs-2015-v-9"><a class="v-9-link" href="#">0,54</a>
					</div>
					<div class="govprogs-2015-v-10"><a class="v-10-link" href="#">0,14</a>
					</div>
					<div class="govprogs-2015-v-11"><a class="v-11-link" href="#">0,04</a>
					</div>
					<div class="govprogs-2015-v-12"><a class="v-12-link" href="#">0,03</a>
					</div>
					<div class="govprogs-2015-v-13"><a class="v-13-link" href="#">0,02</a>
					</div>
					<div class="govprogs-2015-v-14"><a class="v-14-link" href="#">0,018</a>
					</div>
					<div class="farma-v-bar-add">
						<div class="farma-add-btn"></div>
					</div>
				</div>
				<div class="govprogs-legend">
					<div class="legend light-silver">
						<div class="w-row">
							<div class="w-col w-col-1 marker-cell">
								<div class="govprogs-l-1 l-green" data-ix="v-1-show-hide"></div>
							</div>
							<div class="w-col w-col-8 legend-collumn"><a class="govprogs-l-1-link" href="#">Развитие внешнеэкономической деятельности</a>
							</div>
							<div class="w-col w-col-3 num-cell"><a class="govprogs-l-1-link" href="#">141 635,90<br>тыс. руб.</a>
							</div>
						</div>
					</div>
					<div class="legend">
						<div class="w-row">
							<div class="w-col w-col-1 marker-cell">
								<div class="govprogs-l-2 green"></div>
							</div>
							<div class="w-col w-col-8 legend-collumn"><a class="govprogs-l-2-link" href="#">Развитие промышленности и повы- <br>шение ее конкурентоспособности</a>
							</div>
							<div class="w-col w-col-3 num-cell"><a class="govprogs-l-2-link" href="#">130&nbsp;840 379,50 <br>тыс. руб.</a>
							</div>
						</div>
					</div>
					<div class="legend light-silver">
						<div class="w-row">
							<div class="w-col w-col-1 marker-cell">
								<div class="govprogs-l-3 yellow"></div>
							</div>
							<div class="w-col w-col-8 legend-collumn"><a class="govprogs-l-3-link" href="#">Развитие авиационной промыш- <br>ленности на 2013 — 2025 годы</a>
							</div>
							<div class="w-col w-col-3 num-cell"><a class="govprogs-l-3-link" href="#">62&nbsp;085&nbsp;569,60 <br>тыс. руб.</a>
							</div>
						</div>
					</div>
					<div class="legend">
						<div class="w-row">
							<div class="w-col w-col-1 marker-cell">
								<div class="govprogs-l-4 cyan"></div>
							</div>
							<div class="w-col w-col-8 legend-collumn"><a class="govprogs-l-4-link" href="#">Обеспечение общественного порядка<br>и противодействие преступности</a>
							</div>
							<div class="w-col w-col-3 num-cell"><a class="govprogs-l-4-link" href="#">47&nbsp;922,00<br>тыс. руб.</a>
							</div>
						</div>
					</div>
					<div class="legend light-silver bigcell">
						<div class="w-row">
							<div class="w-col w-col-1 marker-cell">
								<div class="govprogs-l-5 darkblue"></div>
							</div>
							<div class="w-col w-col-8 legend-collumn"><a class="govprogs-l-5-link" href="#">Защита населения и территорий от чрезвычайных ситуаций, обеспечение пожарной безопасности и безопасности людей на водных объектах</a>
							</div>
							<div class="w-col w-col-3 num-cell"><a class="govprogs-l-5-link" href="#">900&nbsp;000,00<br>тыс. руб.</a>
							</div>
						</div>
					</div>
					<div class="legend">
						<div class="w-row">
							<div class="w-col w-col-1 marker-cell">
								<div class="govprogs-l-6 velvet"></div>
							</div>
							<div class="w-col w-col-8 legend-collumn"><a class="govprogs-l-6-link" href="#">Развитие судостроения <br>на 2013 — 2030 годы</a>
							</div>
							<div class="w-col w-col-3 num-cell"><a class="govprogs-l-6-link" href="#">9 107 247,80 <br>тыс. руб.</a>
							</div>
						</div>
					</div>
					<div class="legend light-silver mediumcell">
						<div class="w-row">
							<div class="w-col w-col-1 marker-cell">
								<div class="govprogs-l-7 darkred"></div>
							</div>
							<div class="w-col w-col-8 legend-collumn"><a class="govprogs-l-7-link" href="#">Развитие электронной и радиоэлек- <br>тронной промышленности <br>на 2013 — 2025 годы</a>
							</div>
							<div class="w-col w-col-3 num-cell"><a class="govprogs-l-7-link" href="#">12 498 457,00 <br>тыс. руб.</a>
							</div>
						</div>
					</div>
					<div class="legend">
						<div class="w-row">
							<div class="w-col w-col-1 marker-cell">
								<div class="govprogs-l-8 dryblue"></div>
							</div>
							<div class="w-col w-col-8 legend-collumn"><a class="govprogs-l-8-link" href="#" data-ix="govprogs-v-3-show-hint">Развитие фармацевтической и мед. <br>промышленности на 2013 — 2020 годы</a>
							</div>
							<div class="w-col w-col-3 num-cell"><a class="govprogs-l-8-link" href="#">13 090 432,50 <br>тыс. руб.</a>
							</div>
						</div>
					</div>
					<div class="legend light-silver">
						<div class="w-row">
							<div class="w-col w-col-1 marker-cell">
								<div class="govprogs-l-9 darkred"></div>
							</div>
							<div class="w-col w-col-8 legend-collumn"><a class="govprogs-l-9-link" href="#">Космическая деятельность России<br>на 2013 — 2020 годы</a>
							</div>
							<div class="w-col w-col-3 num-cell"><a class="govprogs-l-9-link" href="#">1 494 350,00<br>тыс. руб.</a>
							</div>
						</div>
					</div>
					<div class="legend">
						<div class="w-row">
							<div class="w-col w-col-1 marker-cell">
								<div class="govprogs-l-10 orange"></div>
							</div>
							<div class="w-col w-col-8 legend-collumn"><a class="govprogs-l-10-link" href="#">Развитие атомного энергопромыш- ленного комплекса</a>
							</div>
							<div class="w-col w-col-3 num-cell"><a class="govprogs-l-10-link" href="#">540 625,60<br>тыс. руб.</a>
							</div>
						</div>
					</div>
					<div class="legend light-silver">
						<div class="w-row">
							<div class="w-col w-col-1 marker-cell">
								<div class="govprogs-l-11 red"></div>
							</div>
							<div class="w-col w-col-8 legend-collumn"><a class="govprogs-l-11-link" href="#">Энергоэффективность и развитие <br>энергетики</a>
							</div>
							<div class="w-col w-col-3 num-cell"><a class="govprogs-l-11-link" href="#">22 562,50<br>тыс. руб.</a>
							</div>
						</div>
					</div>
					<div class="legend">
						<div class="w-row">
							<div class="w-col w-col-1 marker-cell">
								<div class="govprogs-l-12 darkblue"></div>
							</div>
							<div class="w-col w-col-8 legend-collumn"><a class="govprogs-l-12-link" href="#">Обеспечение общественного порядка<br>и противодействие преступности</a>
							</div>
							<div class="w-col w-col-3 num-cell"><a class="govprogs-l-12-link" href="#">31&nbsp;922,00<br>тыс. руб.</a>
							</div>
						</div>
					</div>
					<div class="legend light-silver">
						<div class="w-row">
							<div class="w-col w-col-1 marker-cell">
								<div class="govprogs-l-13 lightblue"></div>
							</div>
							<div class="w-col w-col-8 legend-collumn"><a class="govprogs-l-13-link" href="#">Развитие культуры и туризма <br>на 2013 — 2020 годы</a>
							</div>
							<div class="w-col w-col-3 num-cell"><a class="govprogs-l-13-link" href="#">18&nbsp;286,40<br>тыс.руб.</a>
							</div>
						</div>
					</div>
					<div class="legend">
						<div class="w-row">
							<div class="w-col w-col-1 marker-cell">
								<div class="govprog-l-14 pink"></div>
							</div>
							<div class="w-col w-col-8 legend-collumn"><a class="govprogs-l-14-link" href="#">Развитие Северо-Кавказского федераль- <br>ного округа на период до 2025 года</a>
							</div>
							<div class="w-col w-col-3 num-cell"><a class="govprogs-l-14-link" href="#">691&nbsp;000,00<br>тыс. руб.</a>
							</div>
						</div>
					</div>
				</div>
				<div class="govprogs-diag-v-3"></div>
				<div class="govprogs-diag-minus-1"></div>
				<div class="govprogs-diag"></div>
				<div class="govprogs-sugblock">
					<h5>Рекомендуем:</h5><a class="sugblock-link" href="#">Как устроен<br>бюджет</a><a class="sugblock-link" href="#">Ссылка на реле-&nbsp;<br>вантный виджет</a><a class="sugblock-link" href="#">Еще одна ссылка<br>на похожий запрос</a>
				</div>
			</div>
		</div>
		
		<div class="wg-govprogs-set-lg">
			<div class="w-clearfix govprogs-nav-bar-lg">
				<div class="govprogs-set-btn-inside-lg" data-ix="govprogs-settings-hide"></div>
				<div class="govprogs-compare-btn-lg"></div>
			</div>
			<h4 class="invert">Настройка виджета</h4>
			<div class="govprogs-more-btn-lg"><a class="govprogs-more-link-lg black" href="#">Применить</a>
			</div>
		</div>
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		<div class="w-clearfix wg-compare">
			<div class="w-clearfix govprogs-nav-bar-lg">
				<div class="govprogs-set-btn-lg" data-ix="govprogs-settings-show"></div>
				<div class="govprogs-compare-btn-lg" data-ix="hide-compare"></div>
			</div>
			<h4 class="invert">Сравнение:</h4>
			<div class="cm-p-1">
				<div class="cm-p-1-text">Развитие фармацевтической и медицин...</div>
			</div>
			<div class="cm-p-2">
				<div class="cm-p-1-text whitetxt">Расходы на оплату труда персонала МПТ</div>
			</div>
			<div class="w-clearfix cm-p-3">
				<div class="cm-p-1-text whitetxt blacktext">Расходы на развитие ОПК</div>
			</div>
			<div class="cm-p-add" data-ix="add-cmp">
				<div class="cm-p-1-text whitetxt cmadd">+</div>
			</div>
			<div class="cm-timeline">
				<div class="cm-r-tm-2014" data-ix="show-dym-2015"></div>
				<div class="cm-r-tm-2013" data-ix="show-dym-2015"></div>
				<div class="cm-r-tm-2015" data-ix="show-dym-2015"></div>
				<div class="cm-tm-2015" data-ix="show-dym-2015"></div>
				<div class="cm-tm-2014" data-ix="show-dym-2015"></div>
				<div class="cm-tm-2013" data-ix="show-dym-2015"></div>
				<div class="cm-redline"></div>
				<div class="cm-yline"></div>
			</div>
			<div class="govprogs-more-btn-lg cm"><a class="govprogs-more-link-lg black" href="#" data-ix="govprog-farma-show-detail">Из чего состоит сумма</a>
			</div>
			<div class="cm-add">
				<h4>Добавить к сравнению:</h4>
				<div class="cm-select">
					<div class="whitetext select">Расходы на развитие ОПК&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;▼</div>
				</div>
				<div class="cm-ok-btn" data-ix="add-y-line">
					<div class="whitetext select center">Добавить</div>
				</div>
			</div>
		</div>
		<div class="wg-1" data-ix="wg-n-hidden"></div>
		<div class="wg-2" data-ix="wg-n-hidden"></div>
		<div class="wg-sug" data-ix="sug-show"></div>
		<div class="wg-empty-lg" data-ix="show-wg-n">
			<a class="w-inline-block add-wg-linkblock" href="#" data-ix="show-wg-n"></a>
		</div>
		