<form enctype="multipart/form-data" name="form_question" method="post" action="">
    <table>
        <tr>
            <td><label for="name">Ф.И.О./организация:<span style="color: red">*</span></label></td>
            <td><input type="text" class="" name="name" value="" id="name"></td>
        </tr>
        <tr>
            <td><label for="address">Адрес:</label></td>
            <td><input type="text" name="address" id="address" value=""></td>
        </tr>
        <tr>
            <td><label for="email">E-mail:<span style="color: red">*</span></label></td>
            <td><input type="text"  name="email" id="email" value=""></td>
        </tr>
        <tr>
            <td><label for="phone">Телефон</label></td>
            <td><input type="text"  name="phone" id="phone" value=""></td>
        </tr>
        <tr>
            <td><label for="department">Департамент:<span style="color: red">*</span></label></td>
            <td><select  name="department" id="department">
                    <option value=""></option>
                    <option value="Административный департамент">Административный департамент</option>
                    <option value="Департамент авиационной промышленности">Департамент авиационной промышленности</option>
                    <option value="Департамент бюджетной политики и финансов">Департамент бюджетной политики и финансов</option>
                    <option value="Департамент внешнеэкономических отношений">Департамент внешнеэкономических отношений</option>
                    <option value="Департамент государственного регулирования внешнеторговой деятельности">Департамент государственного регулирования внешнеторговой деятельности</option>
                    <option value="Департамент государственной политики в области технического регулирования и обеспечения единства измерений">Департамент государственной политики в области технического регулирования и обеспечения единства измерений</option>
                    <option value="Департамент информационных технологий и общественных связей">Департамент информационных технологий и общественных связей</option>
                    <option value="Департамент станкостроения и инвестиционного машиностроения">Департамент станкостроения и инвестиционного машиностроения</option>
                    <option value="Департамент оборонно-промышленного комплекса">Департамент оборонно-промышленного комплекса</option>
                    <option value="Департамент промышленности обычных вооружений, боеприпасов и спецхимии">Департамент промышленности обычных вооружений, боеприпасов и спецхимии</option>
                    <option value="Департамент радиоэлектронной промышленности">Департамент радиоэлектронной промышленности</option>
                    <option value="Департамент развития внутренней торговли, легкой промышленности и потребительского рынка">Департамент развития внутренней торговли, легкой промышленности и потребительского рынка</option>
                    <option value="Департамент развития фармацевтической и медицинской промышленности">Департамент развития фармацевтической и медицинской промышленности</option>
                    <option value="Департамент реализации конвенционных обязательств">Департамент реализации конвенционных обязательств</option>
                    <option value="Департамент региональной промышленной политики">Департамент региональной промышленной политики</option>
                    <option value="Департамент стратегического развития и проектного управления">Департамент стратегического развития и проектного управления</option>
                    <option value="Департамент судостроительной промышленности и морской техники">Департамент судостроительной промышленности и морской техники</option>
                    <option value="Департамент транспортного и специального машиностроения">Департамент транспортного и специального машиностроения</option>
                    <option value="Департамент химико-технологического и лесопромышленного комплекса">Департамент химико-технологического и лесопромышленного комплекса</option>
                    <option value="Отдел безопасности">Отдел безопасности</option>
                    <option value="Юридический департамент">Юридический департамент</option>
                    <option value="Департамент учета и контроля">Департамент учета и контроля</option>
                    <option value="Департамент металлургии и материалов">Департамент металлургии и материалов</option>
                </select></td>
        </tr>
        <tr>
            <td><label for="question">Тема вопроса:<span style="color: red">*</span></label></td>
            <td><select name="question" id="question">
                    <option value=""></option>
                    <option value="Промышленность">Промышленность</option>
                    <option value="Авиационная промышленность">&nbsp;&nbsp;&nbsp;&nbsp;Авиационная промышленность</option>
                    <option value="Легкая промышленность">&nbsp;&nbsp;&nbsp;&nbsp;Легкая промышленность</option>
                    <option value="Лесопромышленный комплекс">&nbsp;&nbsp;&nbsp;&nbsp;Лесопромышленный комплекс</option>
                    <option value="Металлургия и тяжелое машиностроение">&nbsp;&nbsp;&nbsp;&nbsp;Металлургия и тяжелое машиностроение</option>
                    <option value="Оборонно-промышленный комплекс">&nbsp;&nbsp;&nbsp;&nbsp;Оборонно-промышленный комплекс</option>
                    <option value="Промышленность обычных вооружений, боеприпасов и спецхимии">&nbsp;&nbsp;&nbsp;&nbsp;Промышленность обычных вооружений, боеприпасов и спецхимии</option>
                    <option value="Радиоэлектронная промышленность">&nbsp;&nbsp;&nbsp;&nbsp;Радиоэлектронная промышленность</option>
                    <option value="Судостроительная промышленность">&nbsp;&nbsp;&nbsp;&nbsp;Судостроительная промышленность</option>
                    <option value="Транспортное и специальное машиностроение">&nbsp;&nbsp;&nbsp;&nbsp;Транспортное и специальное машиностроение</option>
                    <option value="Управление в сфере промышленности">&nbsp;&nbsp;&nbsp;&nbsp;Управление в сфере промышленности</option>
                    <option value="Фармацевтическая и медицинская промышленность">&nbsp;&nbsp;&nbsp;&nbsp;Фармацевтическая и медицинская промышленность</option>
                    <option value="Химико-технологический комплекс">&nbsp;&nbsp;&nbsp;&nbsp;Химико-технологический комплекс</option>
                    <option value="Торговля">Торговля</option>
                    <option value="Внутренняя торговля">&nbsp;&nbsp;&nbsp;&nbsp;Внутренняя торговля</option>
                    <option value="Управление в сфере торговли">&nbsp;&nbsp;&nbsp;&nbsp;Управление в сфере торговли</option>
                    <option value="Развитие потребительского рынка">&nbsp;&nbsp;&nbsp;&nbsp;Развитие потребительского рынка</option>
                    <option value="Межотраслевые вопросы">Межотраслевые вопросы</option>
                    <option value="Внешнеэкономические отношения">&nbsp;&nbsp;&nbsp;&nbsp;Внешнеэкономические отношения</option>
                    <option value="Госрегулирование внешнеторговой деятельности">&nbsp;&nbsp;&nbsp;&nbsp;Госрегулирование внешнеторговой деятельности</option>
                    <option value="Изобретательская деятельность">&nbsp;&nbsp;&nbsp;&nbsp;Изобретательская деятельность</option>
                    <option value="Качество предоставления услуг">&nbsp;&nbsp;&nbsp;&nbsp;Качество предоставления услуг</option>
                    <option value="Охрана окружающей среды">&nbsp;&nbsp;&nbsp;&nbsp;Охрана окружающей среды</option>
                    <option value="Реализация конвенционных обязательств">&nbsp;&nbsp;&nbsp;&nbsp;Реализация конвенционных обязательств</option>
                    <option value="Стандартизация и сертификация">&nbsp;&nbsp;&nbsp;&nbsp;Стандартизация и сертификация</option>
                    <option value="Региональная промышленная политика">&nbsp;&nbsp;&nbsp;&nbsp;Региональная промышленная политика</option>
                    <option value="Иное">Иное</option>
                    <option value="Бюджетная политика">&nbsp;&nbsp;&nbsp;&nbsp;Бюджетная политика</option>
                    <option value="Запрос архивной справки">&nbsp;&nbsp;&nbsp;&nbsp;Запрос архивной справки</option>
                    <option value="Информационные технологии">&nbsp;&nbsp;&nbsp;&nbsp;Информационные технологии</option>
                    <option value="Личные вопросы">&nbsp;&nbsp;&nbsp;&nbsp;Личные вопросы</option>
                    <option value="Общественные связи">&nbsp;&nbsp;&nbsp;&nbsp;Общественные связи</option>
                    <option value="Открытые данные">&nbsp;&nbsp;&nbsp;&nbsp;Открытые данные</option>
                    <option value="Социальная сфера">&nbsp;&nbsp;&nbsp;&nbsp;Социальная сфера</option>
                    <option value="Юридические вопросы">&nbsp;&nbsp;&nbsp;&nbsp;Юридические вопросы</option>
                </select></td>
        </tr>
        <tr>
            <td><label for="message">Сообщение:<span style="color: red">*</span></label></td>
            <td><textarea id="message" name="message"></textarea></td>
        </tr>
        <tr>
            <td><label for="file">Прикрепить файл</label></td>
            <td><input type="file"  name="file" id="file"></td>
        </tr>
        <tr>
            <td><input type="submit" class="" value="Отправить"></td>
            <td></td>
        </tr>
    </table> 
</form>