<table>
    <tr><td>Ф.И.О / организация</td><td><?=$this->name?></td></tr>
    <tr><td>Адрес</td><td><?=$this->addredd?></td></tr>
    <tr><td>E-mail</td><td><?=$this->email?></td></tr>
    <tr><td>Телефон</td><td><?=$this->phone?></td></tr>
    <tr><td>Департамент</td><td><?=$this->department?></td></tr>
    <tr><td>Тема вопроса</td><td><?=$this->subject?></td></tr>
    <tr><td>Сообщение</td><td><?=$this->message?></td></tr>
</table>