<?
    $this->bread_crumbs = array(
        (object)array('url' => '/admin/', 'title' => 'Главная'),
        'Пользователи');

    echo Plugin_Message::drawMessage();
    Mikron_Entity_Designer_Toolbar::addTag('a', array('class' => 'btn btn-success button-simple', 'href' => '/organization/new/', 'id' => 'add-org'), 'Зарегистрировать новую организацию...');
?>
<?php
    
    try {

        Mikron_Entity_Designer::drawList('Type_User_Profile');

    } catch(Exception $ex) {
        echo $ex->getMessage();
    }