<?php
    $field_name = $field->name;
    if($field->readonly) {
        ?>
        <?=$item->$field_name ? Format::date(strtotime($item->$field_name)) : Mikron_Entity_Designer::NO_VALUE?>
        <?
    } else {
        ?>		
        <div class="input-append input-group">
          <input type="text" name="form[<?=$field->name?>]" class="<?=implode(' ', $class)?>" value="<?=$item->$field_name?>"  id="<?=$_input_id?>" placeholder="" />
          <a class="btn btn-default" onclick="$(this).prev().focus(); return false;" ><i class="icon icon-calendar"></i></a>
        </div>
		<script>
			$(function(){
				try {
					$('#<?=$_input_id?>').datepicker({
						format    : 'mm.yyyy',
						startView : 'year',
						language  : 'ru'
					}).on('changeMonth', function (ev) {
						$(this).datepicker('update', ev.date);
						$(this).datepicker('hide', true);
						$(this).datepicker('showMode', '1');
					});
					$('#<?=$_input_id?>').datepicker('update', new Date());
				} catch (e) {
					console.log(e);
				}
			});
		</script>
        <?
    }