<?
        $cur_value = htmlspecialchars(Mikron_Entity_Model::getRowValueByPath($item, $field));
	$checked = ($cur_value) ? true : false;
	if(is_array(self::$params->read_only_values)) {
		foreach(self::$params->read_only_values as $fieldname => $fieldvalue) {
			if($fieldname == $field->name) {
				$field->readonly = true;
			}
		}
	}
?>
<input  type="hidden" name="form[<?=$field->name?>]" value="0" />
<input 	type="checkbox"
		id="<?=$_input_id?>"
		name="form[<?=$field->name?>]"
		class="form-control <?=implode(' ', $class)?>"
		value="1"
		<?=$checked ? 'checked="checked"' : null?>
		<?=htmlspecialchars(Mikron_Entity_Model::getRowValueByPath($item, $field))?>
		<?= !$field->readonly ?: 'disabled="disabled"'; ?> />
