<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=1280" />
    <title>Админка</title>
    <link rel="shortcut icon" href="/favicon_admin.ico">
    <!-- JQuery -->
    <script src="/js/jquery-2.1.4.min.js"></script>
    <script src="/js/jquery.form.js"></script>
    <script src="/js/jquery-ui-1.10.3.custom.js"></script>
    <!-- Mikron -->
    <script src="/mikron/mikron.js"></script>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="/bootstrap/3.3.4/dist/css/bootstrap.min.css" />
    <script src="/bootstrap/3.3.4/dist/js/bootstrap.min.js"></script>
    <?/*
    <!-- jQuery.Template -->
    <script type="text/javascript" src="/js/jquery.tmpl.js"></script>
    <script type="text/javascript" src="/js/jquery.tmplPlus.js"></script>
    */?>
    <!-- CustomUI -->
    <link href="/custom-ui/custom-ui.css" media="screen" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="/custom-ui/custom-ui.js"></script>
    <!-- Validator -->
    <link href="/validation/css/validationEngine.jquery.css" media="screen" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="/validation/js/jquery.validationEngine.min.js"></script>
    <script type="text/javascript" src="/validation/js/jquery.validationEngine-ru.js"></script>
    <!-- FormStyler -->
    <script src="/form-styler/jquery.formstyler.js"></script>
    <link href="/form-styler/jquery.formstyler.css" media="screen" rel="stylesheet" type="text/css" />
    <!-- Select2 -->
    <script src="/select2/select2.min.js"></script>
    <script src="/select2/select2_locale_ru.js"></script>
    <link href="/select2/select2.css" media="screen" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="/css/admin.php?v=3" />
    <!-- Datepicker -->
    <link href="/datepicker/datepicker.css" media="screen" rel="stylesheet" type="text/css" />
    <script src="/datepicker/bootstrap-datepicker.js"></script>
    <script src="/datepicker/locales/bootstrap-datepicker.ru.js"></script>
    <script>
        $(function() {
            try {
                // выбор даты
                if($.fn.datepicker != undefined) {
                    $('.datepicker2').datepicker({
                        format: 'dd-mm-yyyy',
                        language: 'ru',
                        autoclose: true,
                        weekStart: 1
                    }).on('changeDate', function(e) {
                       $(this).datepicker('hide');
                    });
                }
                // кастомизация инпутов
                //$('input[type=checkbox], input[type=radio], select, input[type=file], input[type=text], input[type=password], input[type=submit], textarea').styler({
                $('input[type=checkbox], input[type=radio], input[type=file], input[type=text], input[type=password], input[type=submit], textarea').styler({
                    selectVisibleOptions: 20,
                });
                $('.select2').select2({}).one('select2-focus', select2Focus).on("select2-blur", function () {
                    $(this).one('select2-focus', select2Focus)
                });
            } catch(e) {
                alert(e);
            }
        });

        function select2Focus() {
            var select2 = $(this).data('select2');
            setTimeout(function() {
                if (!select2.opened()) {
                    select2.open();
                }
            }, 0);  
        }

    </script>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
    <?// include dirname(__FILE__).'/custom-ui.phtml'?>
</head>
<body>
    <table class="main-table">
        <tr>
            <td colspan="2" style="height: 30px;">
                <nav class="navbar navbar-default" style="margin: 0;">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand brand" href="/admin/">Панель управления</a>
                        </div>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li class="active"><a href="/">вернуться на сайт <span class="sr-only">(current)</span></a></li>
                                <!-- <li><a href="#">Link</a></li> -->
                                <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Быстрые действия <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Действие</a></li>
                                    <li><a href="#">Второе действие</a></li>
                                    <li><a href="#">Третье</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">Совершенно другое</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">Дополнительный раздел</a></li>
                                </ul>
                                </li>
                            </ul>
                            <form class="navbar-form navbar-left" role="search">
                                <div class="form-group">
                                <input type="text" class="form-control" placeholder="Текст для поиска">
                                </div>
                                <button type="submit" class="btn btn-default">Найти</button>
                            </form>
                            <ul class="nav navbar-nav navbar-right">
                                <!-- <li><a href="#">Link</a></li> -->
                                <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Пользователь <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Профиль</a></li>
                                    <!--
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    -->
                                    <li role="separator" class="divider"></li>
                                    <li><a href="/index/logout/">Выйти</a></li>
                                </ul>
                                </li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </div><!-- /.container-fluid -->
                </nav>
            </td>
        </tr>
        <tr>
            <td class="col-sm-2 col-md-2 main-menu">
                <?=Plugin_Menu::draw('menu-admin', 'nav nav-pills nav-stacked')?>
                <?//include dirname(__FILE__).'/block/clock.phtml'?>
            </td>
            <td class="col-sm-10 col-md-10 main-content">
                <?if(isset($this->bread_crumbs)){
                    $last_text = array_pop($this->bread_crumbs);
                    $this->BreadCrumbs($this->bread_crumbs, $last_text);
                }?>
                <div style="padding: 0 20px;">
                    <?=$this->layout()->content?>
                </div>
            </td>
        </tr>
    </table>
</body>
</html>