<!DOCTYPE html>
<!-- © SA&DC | http://www.sa-dc.ru/ -->
<html>
    <head>
        <meta charset="utf-8">
        <title>Открытый бюджет</title>
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <meta name="format-detection" content="telephone=no">
        <link href="css/common.css" rel="stylesheet">
        <link rel="stylesheet" href="/css/style.php?v=1">

    </head>
    <body>
        <div class="education">
            <section class="education__screen education__screen_zero">

                <div class="intro__search">
                    <div class="screen-menu__close js-screen-menu-close"></div>
                    <form class="intro__form">
                        <input type="text" class="intro__form-field" id="search_field">
                        <button type="submit" class="intro__form-submit"  id="search-button">Найти</button>
                    </form>

                    <div class="intro__search-result hidden_block">
                        <span class="intro__search-result-title">Нашлось 3 совпадения:</span>
                        <ul>
                            <li>
                                <a href="javasript:void(0)" class="intro__search-result-link">
                                    Какая доля средств бюджета МПТ выделена в этом году на НИОКР в сфере фармацевтики?
                                </a>
                            </li>
                            <li>
                                <a href="javasript:void(0)" class="intro__search-result-link">
                                    Какая доля средств бюджета МПТ выделена в этом году для развития производства отечественных лекарств?
                                </a>
                            </li>
                            <li>
                                <a href="javasript:void(0)" class="intro__search-result-link">
                                    Какая доля средств бюджета МПТ выделена в этом году для развития производства отечественного медицинского оборудования?
                                </a>
                            </li>
                        </ul>
                    </div>

                </div>

                <div class="intro__search-voice js-voice">
                    <div class="screen-menu__close js-screen-menu-close"></div>

                    <div class="intro__voice">
                        <img src="img/voice.gif">
                        <div class="intro__voice-text">
                            <span class="intro__voice-title">Мы правильно распознали <br> ваш запрос?</span>
                            <span class="intro__voice-query"> Какая доля средств бюджета МПТ выделена <br> в этом году на развитие</span>
                        </div>
                    </div>

                    <div class="intro__search-result intro__search-result_voice">
                        <span class="intro__search-result-title">Нашлось 3 совпадения:</span>
                        <ul>
                            <li>
                                <a href="javasript:void(0)" class="intro__search-result-link">
                                    Какая доля средств бюджета МПТ выделена в этом году на НИОКР в сфере фармацевтики?
                                </a>
                            </li>
                            <li>
                                <a href="javasript:void(0)" class="intro__search-result-link">
                                    Какая доля средств бюджета МПТ выделена в этом году для развития производства отечественных лекарств?
                                </a>
                            </li>
                            <li>
                                <a href="javasript:void(0)" class="intro__search-result-link">
                                    Какая доля средств бюджета МПТ выделена в этом году для развития производства отечественного медицинского оборудования?
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="screen-menu js-screen-menu">
                    <div class="screen-menu__content">

                        <div class="screen-menu__close js-screen-menu-close"></div>
                        <div class="list-menu js-list-menu">
                            <div class="list-menu__topic js-list-menu-topic">
                                <div class="list-menu__item">
                                    <a href="/" class="list-menu__link js-list-menu-link" data-action="main">Главная</a>
                                </div>

                                <div class="list-menu__item" data-action="budget">
                                    <a href="#" class="list-menu__link js-list-menu-link">Бюджет</a>
                                </div>


                                <div class="list-menu__item">
                                    <a href="#" class="list-menu__link js-list-menu-link" data-action="education" data-droplist="true">Обучение</a>
                                </div>
                                <div class="list-menu__detail js-list-menu-detail" data-view="education">
                                    <div class="list-menu__item"><a href="#" class="list-menu__link list-menu__link_detail">Вопросы по бюджету</a></div>
                                    <div class="list-menu__item"><a href="#" class="list-menu__link list-menu__link_detail">Вопросы и ответы</a></div>
                                    <div class="list-menu__item"><a href="#" class="list-menu__link list-menu__link_detail">Норамтивная база</a></div>
                                    <div class="list-menu__item"><a href="#" class="list-menu__link list-menu__link_detail">Документы</a></div>
                                    <div class="list-menu__item"><a href="#" class="list-menu__link list-menu__link_detail">Словарь</a></div>
                                    <div class="list-menu__item"><a href="#" class="list-menu__link list-menu__link_detail">Обучающие тесты</a></div>
                                </div>

                                <div class="list-menu__item">
                                    <a href="#" class="list-menu__link js-list-menu-link" data-action="documents">Документы</a>
                                </div>

                                <div class="list-menu__item">
                                    <a href="#" class="list-menu__link js-list-menu-link" data-action="news">Новости</a>
                                </div>

                                <div class="list-menu__item">
                                    <a href="#" class="list-menu__link js-list-menu-link" data-action="portal">Работа портала</a>
                                </div>

                                <div class="list-menu__item">
                                    <a href="#" class="list-menu__link js-list-menu-link" data-action="contacts">Контакты</a>
                                </div>

                            </div>
                        </div>

                        <div class="footer footer_screen_menu">
                            <div class="footer__left footer__left_page_menu">
                                <div class="footer__copyright footer__copyright_page_menu">© 2015 Минпромторг РФ</div>
                                <adress class="footer__adress footer__adress_page_menu">
                                    inbox@minprom.gov.ru<br>
                                    8 495 539-21-87<br>
                                    Москва, Китайгородский пр., д. 7
                                </adress>
                            </div>
                            <div class="footer__right footer__right_page_menu">
                                <a href="http://minpromtorg.gov.ru/" target="_blank" class="footer__link footer__link_page_menu">Основной сайт Минпромторга</a>
                                <div class="footer__social footer__social_page_menu">
                                    <div class="footer__icon">
                                        <a href="#" class="icon icon-fbook_white"></a>
                                    </div>
                                    <div class="footer__icon">
                                        <a href="#" class="icon icon-vk_white"></a>
                                    </div>
                                    <div class="footer__icon">
                                        <a href="#" class="icon icon-twit_white"></a>
                                    </div>
                                    <div class="footer__icon">
                                        <a href="#" class="icon icon-instagram_white"></a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="appearence">
                            <div class="appearence__title">Внешний вид</div>
                            <div class="appearence__theme">
                                <div class="appearence__item">
                                    <div class="appearence__thumbnail js-appearence-thumbnail">
                                        <img class="appearence__img js-appearence-img" src="img/menu/theme_1.png" alt="img">
                                    </div>
                                    <div class="appearence__text js-appearence-text">Редактировать</div>
                                </div>

                                <div class="appearence__item">
                                    <div class="appearence__thumbnail js-appearence-thumbnail">
                                        <img class="appearence__img js-appearence-img" src="img/menu/theme_2.png" alt="img">
                                    </div>
                                    <div class="appearence__text js-appearence-text">Редактировать</div>
                                </div>

                                <div class="appearence__item">
                                    <div class="appearence__thumbnail js-appearence-thumbnail">
                                        <img class="appearence__img js-appearence-img" src="img/menu/theme_3.png" alt="img">
                                    </div>
                                    <div class="appearence__text js-appearence-text">Редактировать</div>
                                </div>

                                <div class="appearence__item">
                                    <div class="appearence__thumbnail appearence__thumbnail_state_current js-appearence-thumbnail">
                                        <img class="appearence__img js-appearence-img" src="img/menu/theme_4.png" alt="img">
                                    </div>
                                    <div class="appearence__text js-appearence-text">Редактировать</div>
                                </div>
                            </div>

                            <div class="appearence__add-btn"></div>
                        </div>

                    </div>
                </div>
                <header class="header header_type_education">

                    <div class="intro__logo intro__logo_education js-logo">
                        <nav class="header-action header-action_page_main" data-container="menu">
                            <ul class="header-action-list">
                                <li class="header-action-item">
                                    <a href="#" class="header-action-link">
                                        <span class="icon icon-menu js-icon-menu"></span>
                                    </a>
                                </li>
                                <li class="header-action-item">
                                    <a href="#" class="header-action-link">
                                        <span class="icon icon-search js-search-button"></span>
                                    </a>
                                </li>
                                <li class="header-action-item">
                                    <a href="#" class="header-action-link">
                                        <span class="icon icon-voice-search js-voice-search"></span>
                                    </a>
                                </li>
                                <li class="header-action-item">
                                    <a href="#" class="header-action-link" title="Переключение рабочих столов" data-action="switcher">
                                        <span class="icon icon-dashboard js-icon-dashboard"></span>
                                    </a>
                                </li>
                                <li class="header-action-item">
                                    <a class="header-action-link" href="<?= $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'feedback'), null, true); ?>">
                                        <span class="icon icon-help js-icon-help"></span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                        <a href="/" class="logo">
                            <img class="logo__image" src="img/logo.png" alt="МинПромТорг России">
                            <h1 class="logo__name">
                                МинПромТорг России
                            </h1>
                            <div class="logo__text">
                                Открытый бюджет Министерства
                                <br>
                                промышленности и торговли РФ
                            </div>
                        </a>
                        <div class="intro__logo-links js-logo-links">
                            <a href="<?= $this->url(array('module' => 'default', 'controller' => 'desktop', 'action' => 'personal', 'id' => 80), null, true); ?>" class="intro__logo-link">Вход</a>
                            <a href="javascript:void(0)" class="intro__logo-link intro__logo-link_underline">Версия для слабовидящих</a>
                        </div>
                    </div>

                </header>



                <div class="education__wrapper">
                    <div class="education__heading">
                        <h1 class="education__title">Просто о сложном</h1>
                        <div class="education__descript">Добро пожаловать в обучающий раздел. В нем вы легко найдете ответы на вопросы про бюджет. Мы подготовили для вас информацию в простом и понятном для понимания виде.</div>
                    </div>
                    <aside class="education__aside">
                        <h3 class="education__aside-title">Cвежая статья в <a href="#" class="education__aside-title-link">словаре</a>:</h3>
                        <div class="education__aside-item">
                            <div class="education__aside-item-close"></div>
                            <div class="education__aside-title">Госпрограмма</div>
                            <div class="education__aside-item-descript">Cистема мероприятий и инструментов государственной политики, обеспечивающих в рамках реализации. Cистема мероприятий и инструментов государственной политики, обеспечивающих в рамках реализации.
                            </div>
                            <a href="#" class="education__aside-item-link">Читать полностью</a>
                        </div>
                    </aside>
                    <ul class="education__paragraph">
                        <li class="education__paragraph-item">
                            <a href="#" class="education__paragraph-link">Глоссарий</a>
                        </li>

                        <li class="education__paragraph-item">
                            <a href="#" class="education__paragraph-link">Бюджетная система РФ</a>
                        </li>
                        <li class="education__paragraph-item">
                            <a href="#" class="education__paragraph-link">Бюджет минпромторга РФ</a>
                        </li>
                        <li class="education__paragraph-item">
                            <a href="#" class="education__paragraph-link">Нормативная база</a>
                        </li>
                        <li class="education__paragraph-item">
                            <a href="#" class="education__paragraph-link">Справочник по работе с сайтом</a>
                        </li>

                        <li class="education__paragraph-item">
                            <a href="#" class="education__paragraph-link">Тесты</a>
                        </li>
                    </ul>
                </div>
                <div class="education__screen-disabled"></div>
            </section>

            <div class="education__screen-wrapper js-screen-wrapper">

                <div class="education__screen-main">

                    <div class="education__screen-caption">
                        <span class="education__screen-title">
                            Бюджетное устройство
                        </span>
                        <p class="education__screen-text">
                            Основой бюджетного устройства являются экономические отношения и юридические нормы, которые определяют полномочия центральных и местных органов власти по осуществлению бюджетного процесса и по взаимоотношениям между различными видами бюджетов.
                        </p>
                    </div>

                    <div id="struct" class="education__screen-item">
                        <div class="education__screen-item-left">
                            <span class="education__screen-item-title" >
                                КАК УСТРОЕН <br> ФЕДЕРАЛЬНЫЙ БЮДЖЕТ
                            </span>
                            <p class="education__screen-item-text">
                                Бюджет — форма образования и расходования денежных средств, которые предназначены для финансового обеспечения задач и функций государства и местного самоуправления.
                            </p>
                            <p class="education__screen-item-text">
                                Главное требование, предъявляемое к органам, составляющим и утверждающим бюджет — его сбалансированность по доходам и расходам.
                            </p>
                        </div>
                        <div class="education__screen-item-right">
                            <img class = "education__screen-item-image" src="img/education/1.png">
                        </div>
                    </div>
                    <div class="education__screen-item-separator">
                    </div>

                    <div class="education__screen-item">
                        <span class="education__screen-item-title education__screen-item-title_centered" >
                            ЧТО ТАКОЕ <br> БЮДЖЕТНЫЙ ПРОЦЕСС
                        </span>
                        <p class="education__screen-item-text education__screen-item-text_centered">
                            Бюджетный процесс — это регулируемая законом деятельность органов государственной власти и местного самоуправления по составлению, рассмотрению, утверждению  и исполнению бюджетов соответствующих уровней. Бюджетный процесс на примере бюджета 2015 года включает следующие этапы:
                        </p>
                    </div>

                    <div class="education__screen-steps">
                        <div class="education__screen-steps-left">

                        </div>
                        <div class="education__screen-steps-center">
                            <img class="education__screen-steps-image" src="img/education/Gant.png">
                        </div>
                        <div class="education__screen-steps-right"></div>
                    </div>

                    <div class="education__screen-item">
                        <div class="education__screen-item-columns">
                            <div class="education__screen-item-column education__screen-item-column_first">
                                <div class="education__screen-item-title-wrapper">
                                    <span class="education__screen-item-column-title">Составление <br>проекта <br> бюджета <br> на 2015 год:</span>
                                </div>
                                <p>До 1 октября 2014 г.<br>
                                    На этом этапе на основе прогноза социально-эконо- мического развития государ- ства определяются основные  параметры бюджета на пред- стоящий финансовый год  и плановый период. На этом  этапе также вырабатываются  налоговая, бюджетная и денеж- но-кредитная политика, мето- ды и источники покрытия дефи- цита бюджета, долговая политика государства. На этом этапе  распределяются бюджетные  ассигнования.</p>
                            </div>
                            <div class="education__screen-item-column education__screen-item-column_second">
                                <div class="education__screen-item-title-wrapper">
                                    <span class="education__screen-item-column-title">Рассмотрение <br> и утверждение <br> бюджета на <br> 2015 год</span>
                                </div>
                                <p>1 октября — 1 декабря 2014 г.<br>
                                    На этом этапе подготовленныепроекты бюджетов рассматриваются в трех чтениях Государственной Думой и Советом Федерации и утверждаются послесогласования всех спорных вопросов. После одобренияпроекты бюджетов направляются Советом Федерации Федерального Собрания Российской Федерации на подпись Президенту оссийской Федерации. Подписанный Президентом Российской Федерации проект бюджетастановится федеральнымзаконом.</p>
                            </div>
                            <div class="education__screen-item-column education__screen-item-column_third">
                                <div class="education__screen-item-title-wrapper">
                                    <span class="education__screen-item-column-title">Исполнение<br>бюджета:</span>
                                </div>

                                <p>1 января — 31 декабря 2015 г.<br>
                                    Исполнение федерального бюджета РФ обеспечивается Правительством Российской Федерации. Основа для испол-нения бюджета - сводная бюд-жетная роспись и кассовый план.</p>
                            </div>
                            <div class="education__screen-item-column education__screen-item-column_four">
                                <div class="education__screen-item-title-wrapper">
                                    <span class="education__screen-item-column-title">Подготовка, рассмотре-<br>ние и утверждение<br>отчета об исполнении <br>бюджета</span>
                                </div>
                                <p>1 апреля — 1 октября 2016 г.<br>
                                    На данном этапе участниками бюджетного процесса проводится подготовка и составление отчетности об исполнении бюджетов. <br>По итогам финансового годасоставляется бюджетная отчетность, направляемая для проверкив органы государственного финансового контроля, а затем на рассмотрение и утверждение в законодательные и представительные органы.</p>
                            </div>
                        </div>
                    </div>



                    <div class="education__screen-item-separator">
                    </div>
                    <div class="education__screen-item">
                        <span class="education__screen-item-title education__screen-item-title_lefted" >
                            ЧТО ТАКОЕ<br>БЮДЖЕТНАЯ<br>СИСТЕМА?
                        </span>
                        <p class="education__screen-item-text education__screen-item-text_lefted">
                            Бюджетная система Российской Федерации — это совокупность федерального бюджета, бюджетов субъектов Российской Федерации, местных бюджетов и бюджетов государственных внебюджетных фондов. Работа бюджетной системы регулируется законодательством РФ.
                        </p>
                        <img class="education__screen-image education__screen-image" src="img/education/2.png">
                    </div>
                    <div class="education__screen-item-separator">
                    </div>

                    <div class="education__screen-item education__screen-item_normal">
                        <span class="education__screen-item-title education__screen-item-title_centered education__screen-item-title_blocks" >
                            Кто участвует в бюджетном процессе
                        </span>
                        <img class="education__screen-image" src="img/education/4.png">
                    </div>
                    <div class="education__screen-item-separator">
                    </div>

                    <div class="education__screen-item education__screen-item_full">
                        <span class="education__screen-item-title education__screen-item-title_centered education__screen-item-title_blocks" >
                            КТО, КАК И КОГДА ПРИНИМАЕТ БЮДЖЕТ МИНПРОМТОРГА РОССИИ?
                        </span>
                        <img class="education__screen-image education__screen-image_full" src="img/education/6.png">
                    </div>
                    <div class="education__screen-item-separator">
                    </div>

                    <div id="diff" class="education__screen-item education__screen-item_normal">
                        <span class="education__screen-item-title education__screen-item-title_centered education__screen-item-title_blocks" >
                            БЮДЖЕТ МИНПРОМТОРГА И ФЕДЕРАЛЬНЫЙ <br> БЮДЖЕТ — В ЧЕМ РАЗНИЦА?
                        </span>
                        <img class="education__screen-image" src="img/education/5.png">
                    </div>

                </div>
            </div>

            <footer class="footer footer_page_faq">
                <div class="footer__left">
                    <div class="footer__copyright">© 2015 Минпромторг РФ</div>
                    <adress class="footer__adress">
                        <a class="footer__left-link" href="mailto:inbox@minprom.gov.ru">inbox@minprom.gov.ru</a>
                        <br>
                        <a class="footer__left-link" href="tel:84955392187">8 495 539-21-87</a>
                        <br>
                        Москва, Китайгородский пр., д. 7
                    </adress>
                </div>
                <div class="footer__right">
                    <a href="http://minpromtorg.gov.ru/" target="_blank" class="footer__link">Основной сайт Минпромторга</a>
                    <div class="footer__social">
                        <div class="footer__social">
                            <div class="footer__icon">
                                <a href="https://www.facebook.com/minpromtorg" target="_blank" class="icon icon-fbook"></a>
                            </div>
                            <div class="footer__icon">
                                <a href="http://vk.com/minpromtorgrus" target="_blank" class="icon icon-vk"></a>
                            </div>
                            <div class="footer__icon">
                                <a href="https://twitter.com/minpromtorg_rus" target="_blank" class="icon icon-twit"></a>
                            </div>
                            <div class="footer__icon">
                                <a href="https://instagram.com/minpromtorg/" target="_blank" class="icon icon-instagram"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
            <script src="js/lib/jquery.js"></script>
            <script src="http://code.highcharts.com/highcharts.js"></script>
            <script src="http://code.highcharts.com/modules/exporting.js"></script>
            <script src="js/common.js"></script>
            <script src="/js/jquery.autocomplete.js"></script>
            <script src="/js/other.js"></script>
    </body>
</html>

