<!DOCTYPE html>
<!-- © SA&DC | http://www.sa-dc.ru/ -->
<html>
    <head>
        <meta charset="utf-8">
        <title>Открытый бюджет</title>
<!--        <meta name="viewport" content="width=1280">-->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="format-detection" content="telephone=no">
        <!-- temp -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.0.8/css/swiper.css" rel="stylesheet">
        <!-- /temp -->
        <link href="css/common.css" rel="stylesheet">
        <link href="css/jelect.css" rel="stylesheet">
        <!-- Style -->
        <link rel="stylesheet" href="/css/style.php?v=1">
        <script src="/js/jquery-latest.js"></script>
        <script src="/js/jquery.autocomplete.js"></script>
        <script src="/js/other.js"></script>
        <script src="http://code.highcharts.com/highcharts.js"></script>
        <script src="http://code.highcharts.com/highcharts-3d.js"></script>
        <script src="http://code.highcharts.com/modules/exporting.js"></script>
        <script src="http://code.highcharts.com/maps/modules/map.js"></script>
        <script src="http://code.highcharts.com/maps/modules/data.js"></script>
        <script src="http://code.highcharts.com/maps/modules/drilldown.js"></script>
        <!-- <script src="http://code.highcharts.com/mapdata/countries/ru/ru-all.js"></script> -->
        <script src="/mapdata/original"></script>
    </head>
    <body class="is-main">
        <div class="page js-page">

            <section class="intro swiper-container" id="intro">

                <div class="intro__search">
                    <div class="screen-menu__close js-screen-menu-close"></div>
                    <form class="intro__form">
                        <input type="text" class="intro__form-field" id="search_field">

                        <button type="submit" class="intro__form-submit"  id="search-button">Найти</button>
                    </form>

                    <div class="intro__search-result hidden_block">
                        <span class="intro__search-result-title">Нашлось 3 совпадения:</span>
                        <ul>
                            <li>
                                <a href="javasript:void(0)" class="intro__search-result-link">
                                    Какая доля средств бюджета МПТ выделена в этом году на НИОКР в сфере фармацевтики?
                                </a>
                            </li>
                            <li>
                                <a href="javasript:void(0)" class="intro__search-result-link">
                                    Какая доля средств бюджета МПТ выделена в этом году для развития производства отечественных лекарств?
                                </a>
                            </li>
                            <li>
                                <a href="javasript:void(0)" class="intro__search-result-link">
                                    Какая доля средств бюджета МПТ выделена в этом году для развития производства отечественного медицинского оборудования?
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="intro__search-voice js-voice">
                    <div class="screen-menu__close js-screen-menu-close"></div>

                    <div class="intro__voice">
                        <img src="img/voice.gif">
                        <div class="intro__voice-text">
                            <span class="intro__voice-title">Мы правильно распознали <br> ваш запрос?</span>
                            <span class="intro__voice-query"> Какая доля средств бюджета МПТ выделена <br> в этом году на развитие</span>
                        </div>
                    </div>

                    <div class="intro__search-result intro__search-result_voice">
                        <span class="intro__search-result-title">Нашлось 3 совпадения:</span>
                        <ul>
                            <li>
                                <a href="javasript:void(0)" class="intro__search-result-link">
                                    Какая доля средств бюджета МПТ выделена в этом году на НИОКР в сфере фармацевтики?
                                </a>
                            </li>
                            <li>
                                <a href="javasript:void(0)" class="intro__search-result-link">
                                    Какая доля средств бюджета МПТ выделена в этом году для развития производства отечественных лекарств?
                                </a>
                            </li>
                            <li>
                                <a href="javasript:void(0)" class="intro__search-result-link">
                                    Какая доля средств бюджета МПТ выделена в этом году для развития производства отечественного медицинского оборудования?
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="screen-menu js-screen-menu">
                    <div class="screen-menu__content">

                        <div class="screen-menu__close js-screen-menu-close"></div>
                        <div class="list-menu js-list-menu">
                            <div class="list-menu__topic js-list-menu-topic">
                                <div class="list-menu__item">
                                    <a href="/" class="list-menu__link js-list-menu-link" data-action="main">Главная</a>
                                </div>

                                <div class="list-menu__item" data-action="budget">
                                    <a href="#" class="list-menu__link js-list-menu-link">Бюджет</a>
                                </div>


                                <div class="list-menu__item">
                                    <a href="#" class="list-menu__link js-list-menu-link" data-action="education" data-droplist="true">Обучение</a>
                                </div>
                                <div class="list-menu__detail js-list-menu-detail" data-view="education">
                                    <div class="list-menu__item"><a href="/education" class="list-menu__link list-menu__link_detail">Вопросы по бюджету</a></div>
                                    <div class="list-menu__item"><a href="#" class="list-menu__link list-menu__link_detail">Вопросы и ответы</a></div>
                                    <div class="list-menu__item"><a href="#" class="list-menu__link list-menu__link_detail">Норамтивная база</a></div>
                                    <div class="list-menu__item"><a href="#" class="list-menu__link list-menu__link_detail">Документы</a></div>
                                    <div class="list-menu__item"><a href="#" class="list-menu__link list-menu__link_detail">Словарь</a></div>
                                    <div class="list-menu__item"><a href="#" class="list-menu__link list-menu__link_detail">Обучающие тесты</a></div>
                                </div>

                                <div class="list-menu__item">
                                    <a href="#" class="list-menu__link js-list-menu-link" data-action="documents">Документы</a>
                                </div>

                                <div class="list-menu__item">
                                    <a href="#" class="list-menu__link js-list-menu-link" data-action="news">Новости</a>
                                </div>

                                <div class="list-menu__item">
                                    <a href="#" class="list-menu__link js-list-menu-link" data-action="portal">Работа портала</a>
                                </div>

                                <div class="list-menu__item">
                                    <a href="#" class="list-menu__link js-list-menu-link" data-action="contacts">Контакты</a>
                                </div>

                            </div>
                        </div>

                        <div class="footer footer_screen_menu">
                            <div class="footer__left footer__left_page_menu">
                                <div class="footer__copyright footer__copyright_page_menu">© 2015 Минпромторг РФ</div>
                                <adress class="footer__adress footer__adress_page_menu">
                                    inbox@minprom.gov.ru<br>
                                    8 495 539-21-87<br>
                                    Москва, Китайгородский пр., д. 7
                                </adress>
                            </div>
                            <div class="footer__right footer__right_page_menu">
                                <a href="http://minpromtorg.gov.ru/" target="_blank" class="footer__link footer__link_page_menu">Основной сайт Минпромторга</a>
                                <div class="footer__social footer__social_page_menu">
                                    <div class="footer__icon">
                                        <a href="https://www.facebook.com/minpromtorg" target="_blank" class="icon icon-fbook_white"></a>
                                    </div>
                                    <div class="footer__icon">
                                        <a href="http://vk.com/minpromtorgrus" target="_blank" class="icon icon-vk_white"></a>
                                    </div>
                                    <div class="footer__icon">
                                        <a href="https://twitter.com/minpromtorg_rus" target="_blank" class="icon icon-twit_white"></a>
                                    </div>
                                    <div class="footer__icon">
                                        <a href="https://instagram.com/minpromtorg/" target="_blank" class="icon icon-instagram_white"></a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="appearence">
                            <div class="appearence__title">Внешний вид</div>
                            <div class="appearence__theme">
                                <div class="appearence__item">
                                    <div class="appearence__thumbnail js-appearence-thumbnail">
                                        <img class="appearence__img js-appearence-img" src="img/menu/theme_1.png" alt="img">
                                    </div>
                                    <div class="appearence__text js-appearence-text">Редактировать</div>
                                </div>

                                <div class="appearence__item">
                                    <div class="appearence__thumbnail js-appearence-thumbnail">
                                        <img class="appearence__img js-appearence-img" src="img/menu/theme_2.png" alt="img">
                                    </div>
                                    <div class="appearence__text js-appearence-text">Редактировать</div>
                                </div>

                                <div class="appearence__item">
                                    <div class="appearence__thumbnail js-appearence-thumbnail">
                                        <img class="appearence__img js-appearence-img" src="img/menu/theme_3.png" alt="img">
                                    </div>
                                    <div class="appearence__text js-appearence-text">Редактировать</div>
                                </div>

                                <div class="appearence__item">
                                    <div class="appearence__thumbnail appearence__thumbnail_is_active js-appearence-thumbnail">
                                        <img class="appearence__img js-appearence-img" src="img/menu/theme_4.png" alt="img">
                                    </div>
                                    <div class="appearence__text js-appearence-text appearence__text_is_active">Редактировать</div>
                                </div>
                            </div>

                            <div class="appearence__add-btn"></div>
                        </div>

                    </div>
                </div>


                <div class="intro__logo js-logo">
                    <nav class="header-action header-action_page_main" data-container="menu">
                        <ul class="header-action-list">
                            <li class="header-action-item">
                                <div class="header-action-link">
                                    <span class="icon icon-menu js-icon-menu"></span>
                                </div>
                            </li>
                            <li class="header-action-item">
                                <div class="header-action-link">
                                    <span class="icon icon-search js-search-button"></span>
                                </div>
                            </li>
                            <li class="header-action-item">
                                <div class="header-action-link">
                                    <span class="icon icon-voice-search js-voice-search"></span>
                                </div>
                            </li>
                            <li class="header-action-item">
                                <div class="header-action-link" title="Переключение рабочих столов" data-action="switcher">
                                    <span class="icon icon-dashboard js-icon-dashboard"></span>
                                </div>
                            </li>
                            <li class="header-action-item">
                                <div class="header-action-link">
                                    <a href="<?= $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'feedback'), null, true); ?>"><span class="icon icon-help js-icon-help"></span></a>
                                </div>
                            </li>
                        </ul>
                    </nav>
                    <a href="/" class="logo">
                        <img class="logo__image" src="img/logo.png" alt="МинПромТорг России">
                        <h1 class="logo__name">
                            МинПромТорг России
                        </h1>
                        <div class="logo__text">
                            Открытый бюджет Министерства
                            <br>
                            промышленности и торговли
                        </div>
                    </a>
                    <div class="intro__logo-links js-logo-links">
                        <a href="<?= $this->url(array('module' => 'default', 'controller' => 'desktop', 'action' => 'personal', 'id' => 80), null, true); ?>" class="intro__logo-link">Вход</a>
                        <a href="javascript:void(0)" class="intro__logo-link intro__logo-link_underline">Версия для слабовидящих</a>
                    </div>
                </div>

                <div class="intro__wrapper swiper-wrapper">

                    <div class="swiper-slide">
                        <div class="intro__scene">
                            <div
                                class="intro__layer intro__layer_type_back"
                                style="background-image: url(img/intro/fighter/fighter-back.jpg);"
                                ></div>
                            <div class="intro__layer intro__layer_type_title">
                                <h3 class="intro-title">
                                    Новая техника
                                    <br>
                                    <span class="intro-title__hl intro-title__hl_underline_not">для вооруженных
                                        <br>сил
                                    </span>
                                </h3>
                            </div>
                            <div
                                class="intro__layer intro__layer_type_front"
                                style="background-image: url(img/intro/fighter/fighter-font.png);"
                                ></div>
                        </div>
                    </div>

                    <div class="swiper-slide">
                        <div class="intro__scene">
                            <div
                                class="intro__layer intro__layer_type_back"
                                style="background-image: url(img/intro/worker/worker-back.jpg);"
                                ></div>
                            <div class="intro__layer intro__layer_type_title">
                                <h3 class="intro-title intro-title_worker">
                                    Новые
                                    <br>
                                    <span class="intro-title__hl intro-title__hl_underline_not">
                                        <span class="intro-title__hl_underline">
                                            рабочие
                                        </span>
                                        <span class="intro-title__hl_underline">
                                            места
                                        </span>
                                    </span>
                                </h3>
                            </div>
                            <div
                                class="intro__layer intro__layer_type_front intro__layer_type_worker"
                                style="background-image: url(img/intro/worker/worker-front.png);"
                                ></div>
                        </div>
                    </div>

                </div>
            </section>

            <div class="page-inner">
                <div class="page-content">
                    <?= $this->layout()->content ?>			
                </div>
                <div class="widget__aside widget__aside_main">
                    <div class="widget__aside-title">Интересные запросы <br> к бюджету минпроторга <br> рф</div>

                    <div class="widget__aside-item">
                        <a href="<?= $this->url(array('module' => 'default', 'controller' => 'desktop', 'action' => 'personal', 'id' => 140), null, true); ?>" class="widget__aside-item-description">
                            <img src="img/widget/1.jpg" class="widget__aside-img" alt="image">
                            Сколько средств  в этом году выделено на развитие отечественных лекарств?
                        </a>
                    </div>

                    <div class="widget__aside-item">
                        <a href="<?= $this->url(array('module' => 'default', 'controller' => 'desktop', 'action' => 'personal', 'id' => 80), null, true); ?>" class="widget__aside-item-description">
                            <img src="img/widget/2.jpg" class="widget__aside-img" alt="image">
                            Бюджет госпрограмм на 2015 год
                        </a>
                    </div>

                    <div class="widget__aside-item">
                        <a href="#" class="widget__aside-item-description">
                            <img src="img/widget/3.jpg" class="widget__aside-img" alt="image">
                            Продукция высококачественных отраслей
                        </a>
                    </div>

                    <div class="widget__aside-item">
                        <a href="#" class="widget__aside-item-description">
                            <img src="img/widget/4.jpg" class="widget__aside-img" alt="image">
                            Сколько средств в этом году выделено на развитие отечественных лекарств?
                        </a>
                    </div>

                    <div class="widget__aside-item">
                        <a href="#" class="widget__aside-item-description">
                            <img src="img/widget/5.jpg" class="widget__aside-img" alt="image">
                            Бюджет госпрограмм на 2015 год
                        </a>
                    </div>

                    <div class="widget__aside-item">
                        <a href="#" class="widget__aside-item-description">
                            <img src="img/widget/6.jpg" class="widget__aside-img" alt="image">
                            Продукция высококачественных отраслей
                        </a>
                    </div>

                    <div class="widget__aside-item">
                        <a href="#" class="widget__aside-item-description">
                            <img src="img/widget/7.jpg" class="widget__aside-img" alt="image">
                            Сколько средств в этом году выделено на развитие отечественных лекарств?
                        </a>
                    </div>

                    <div class="widget__aside-item">
                        <a href="#" class="widget__aside-item-description">
                            <img src="img/widget/8.jpg" class="widget__aside-img" alt="image">
                            Бюджет госпрограмм на 2015 год
                        </a>
                    </div>

                    <div class="widget__aside-item">
                        <a href="#" class="widget__aside-item-description">
                            <img src="img/widget/9.jpg" class="widget__aside-img" alt="image">
                            Продукция высококачественных отраслей
                        </a>
                    </div>

                    <div class="widget__aside-item">
                        <a href="#" class="widget__aside-item-description">
                            <img src="img/widget/10.jpg" class="widget__aside-img" alt="image">
                            Сколько средств в этом году выделено на развитие отечественных лекарств?
                        </a>
                    </div>

                    <div class="widget__aside-item">
                        <a href="#" class="widget__aside-item-description">
                            <img src="img/widget/11.jpg" class="widget__aside-img" alt="image">
                            Продукция высококачественных отраслей
                        </a>
                    </div>

                    <div class="widget__aside-item">
                        <a href="#" class="widget__aside-item-description">
                            <img src="img/widget/12.jpg" class="widget__aside-img" alt="image">
                            Сколько средств в этом году выделено на развитие отечественных лекарств?
                        </a>
                    </div>
                </div>
            </div>
            <section class="infoslider swiper-container" id="infoslider">
                <h2 class="infoslider__slogan">
                    Российская промышленность:
                    <br>
                    достижения
                </h2>
                <div class="infoslider__wrapper swiper-wrapper">

                    <div
                        class="infoslider__slide swiper-slide"
                        style="background-image: url(img/infoslider/mi-8.jpg);"
                        >
                        <h3 class="infoslider__title infoslider__title_footer">
                            Импортозамещение
                            <br>
                            в авиапромыш-
                            <br>
                            <span class="infoslider__title-hl">ленности</span>
                        </h3>
                        <div class="infoslider__share">
                            <a href="javascript:void(0);" class="infoslider__share-link">Узнать больше</a>
                        </div>
                        <div class="infoslider__about">
                            <p class="infoslider__text">
                                В рамках реализации мероприятий по импортозамещению Госпрограммы
                                «Развитие авиационной промышленности» в 2014 году на вертолетах Ми-
                                8АМТШ-В импортное оборудование было заменено на оборудование
                                российского производства. Применение российского оборудования
                                позволило добиться существенных улучшений характеристик вертолета.
                                <br>
                                <br>
                            </p>
                            <p class="infoslider__text">
                                Вертолеты Ми-8АМТШ-В производятся холдингом «Вертолеты России» на авиационном заводе в Улан-Удэ.
                            </p>
                            <div class="infoslider__more">
                                <a href="javascript:void(0);" class="infoslider__read">Читать полностью</a>
                            </div>
                        </div>
                    </div>
                    <div
                        class="infoslider__slide swiper-slide"
                        style="background-image: url(img/infoslider/moscow.jpg);"
                        >
                        <h3 class="infoslider__title infoslider__title_footer">
                            Ледокол
                            <br>
                            <span class="infoslider__title-hl">«Москва»</span>
                        </h3>
                        <div class="infoslider__share">
                            <a href="javascript:void(0);" class="infoslider__share-link">Узнать больше</a>
                        </div>
                        <div class="infoslider__about">
                            <p class="infoslider__text">
                                Государственная программа «Развитие судостроения» предусматривает
                                комплекс мероприятий по совершенствованию ледокольного флота. В 2005-
                                2009 годах ОАО «Балтийский завод» построены два ледокола проекта 21900.
                                В настоящий момент строительство еще трех модернизированных ледоколов
                                проекта 21900М ведется на ОАО «Выборгский судостроительный завод».
                                <br>
                                <br>
                            </p>
                            <div class="infoslider__more">
                                <a href="javascript:void(0);" class="infoslider__read">Читать полностью</a>
                            </div>
                        </div>
                    </div>
                    <div
                        class="infoslider__slide swiper-slide"
                        style="background-image: url(img/infoslider/farma.jpg);"
                        >
                        <h3 class="infoslider__title infoslider__title_footer">
                            Фармацевтический
                            <br>
                            завод компании
                            <br>
                            <span class="infoslider__title-hl infoslider__title_footer">«Ниармедик Фарма»</span>
                        </h3>
                        <div class="infoslider__share">
                            <a href="javascript:void(0);" class="infoslider__share-link">Узнать больше</a>
                        </div>
                        <div class="infoslider__about">
                            <p class="infoslider__text">
                                Реализация мер государственной поддержки в рамках Госпрограммы
                                «Развитие фармацевтической и медицинской промышленности» позволила 						удержать и нарастить долю отечественных препаратов на российском  						фармацевтическом рынке с опережением прогнозных показателей.
                                <br>
                                <br>
                            </p>
                            <p class="infoslider__text">
                                В июне 2015 года компанией «Ниармедик Фарма» в Обнинске открыто
                                производство лекарственных препаратов. Завод будет выпускать до 100
                                миллионов упаковок различных лекарственных препаратов в год.
                                Производство включает полный цикл от синтеза исходных веществ до
                                выпуска готовых препаратов.
                            </p>
                            <div class="infoslider__more">
                                <a href="javascript:void(0);" class="infoslider__read">Читать полностью</a>
                            </div>
                        </div>
                    </div>
                    <div
                        class="infoslider__slide swiper-slide"
                        style="background-image: url(img/infoslider/elbrus.jpg);"
                        >
                        <h3 class="infoslider__title infoslider__title_footer">
                            Российский супер-
                            <br>
                            компьютер на базе
                            <br>
                            процессоров
                            <br>
                            <span class="infoslider__title-hl">«Эльбрус»</span>
                        </h3>
                        <div class="infoslider__share">
                            <a href="javascript:void(0);" class="infoslider__share-link">Узнать больше</a>
                        </div>
                        <div class="infoslider__about">
                            <p class="infoslider__text">
                                В рамках реализации мероприятий Госпрограммы «Развитие электронной и
                                радиоэлектронной промышленности» компанией «МЦСТ» создан
                                вычислительный комплекс класса Супер-ЭВМ на базе 256 четырехъядерных
                                процессоров российского производства «Эльбрус-4С». Производительность
                                этой вычислительной системы класса Супер-ЭВМ равна 13,8 Тфлопс.
                            </p>
                            <div class="infoslider__more">
                                <a href="javascript:void(0);" class="infoslider__read">Читать полностью</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="infoslider__button infoslider__button_dir_next js-swiper-next"></div>
                <div class="infoslider__button infoslider__button_dir_prev js-swiper-prev"></div>
            </section>

            <footer class="footer">
                <div class="footer__left">
                    <div class="footer__copyright">© 2015 Минпромторг РФ</div>
                    <adress class="footer__adress">
                        <a class="footer__left-link" href="mailto:inbox@minprom.gov.ru">inbox@minprom.gov.ru</a>
                        <br>
                        <a class="footer__left-link" href="tel:84955392187">8 495 539-21-87</a>
                        <br>
                        Москва, Китайгородский пр., д. 7
                    </adress>
                </div>
                <div class="footer__right">
                    <a href="http://minpromtorg.gov.ru/" target="_blank" class="footer__link">Основной сайт Минпромторга</a>
                    <div class="footer__social">
                        <div class="footer__icon">
                            <a href="https://www.facebook.com/minpromtorg" target="_blank" class="icon icon-fbook"></a>
                        </div>
                        <div class="footer__icon">
                            <a href="http://vk.com/minpromtorgrus" target="_blank" class="icon icon-vk"></a>
                        </div>
                        <div class="footer__icon">
                            <a href="https://twitter.com/minpromtorg_rus" target="_blank" class="icon icon-twit"></a>
                        </div>
                        <div class="footer__icon">
                            <a href="https://instagram.com/minpromtorg/" target="_blank" class="icon icon-instagram"></a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        <script src="js/lib/jquery.jelect.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.0.8/js/swiper.min.js"></script>
        <script src="js/main.js"></script>
    </body>
</html>
