        <tr>
            <td class="footer" colspan="2">
                <table style="float: right;">
                <tr>
                <td style="text-align: right; padding-right: 1em;">
                    <a href="http://etton.ru/" target="blank" title="ООО «Эттон»">&copy; «Эттон» 2010 &ndash; <?=date('Y', time())?></a>
                    <br>Все права защищены
                </td>
                <td>
                    <img src="/img/ettonlogo.png" alt="ООО Эттон" />
                </td>
                </tr>
                </table>
                <br style="clear: both;" />
            </td>
        </tr>