<tr style="height: 1px;">
    <td colspan="2" style="height: 0px; padding: 20px 10px;">
        <table style="width: 100%;">
            <tr>
                <td style="width: 16px;">
                    <a href="//<?=Settings::get('root_domain')?>/"><i class="topanel"></i></a>
                </td>
                <td style="padding: 10px; width: 32px;">
					<img src="/img/3-inspect.png" />
				</td>
				<td class="mmenu" style="max-width: 35%;">
					<div class="dropdown project-title">
						<span style="line-height: 1.2em;" class="dropdown-toggle" data-toggle="dropdown" href="#">
							<span style="color: #3586d0; font-size: 18pt;">Жилищная инспекция <img src="/img/ddcar.png" /></span><br />
							<span style="font-size: 8pt;">Электронный документооборот Государственной жилищной инспекции</span>
						</span>
						<?= Plugin_Menu::draw('project-menu', 'dropdown-menu') ?>
					</div>
                </td>
                <td style="text-align: left;">
                    <?if(property_exists($this, 'header_title')){?>
                        <?=htmlspecialchars($this->header_title)?>
                    <?}?>
                    <?/*
                    <? if(isset($this->hide_program) && !$this->hide_program) { ?>
                        <?= isset($this->program_title) ? $this->program_title : '' ?>
                        <?=$this->program->year ? DateTime::createFromFormat('Y-m-d', $this->program->year)->format('Y') : null?>
                        <?if(property_exists($this, 'home')) {?>
                            <br /><?= htmlspecialchars($this->home->address_string) ?>
                        <?}?>
                        <?if(property_exists($this->program, 'count')) {?>
                            <br /><span class="small font-no-data">(домов: <?= htmlspecialchars($this->program->count) ?>)</span>
                        <?}?>
                        <br /><a href="<?if(isset($this->program)){ echo $this->program->parent_id ? '/list/short' : '/list/long'; }?>" style="text-decoration: underline; font-size: 10pt">к списку программ</a>
                    <? } ?>
                    */?>
                </td>
                <td style="width: 15em;">
                    <div style="float: right; clear: both; padding-right: .5em;">
                        <div class="dropdown">
                            <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="#"><?=htmlspecialchars($this->user->getInfo()->organization_title)?> <b class="caret"></b></a>
                            <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dLabel">
                                <li><a href="/profile/">Профиль</a></li>
                                <li class="divider"></li>
                                <li><a href="//<?=Settings::get('root_domain')?>/index/logout/">Выход</a></li>
                            </ul>
                        </div>
                    </div>
			    </td>
            </tr>
        </table>
    </td>
</tr>