<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1280" />
    <title><?=SITE_TITLE?></title>
    <!-- Favicon -->
    <link rel="shortcut icon" href="/favicon.ico" />
    <!-- <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tahoma"> -->
    <!-- Jquery -->
    <script src="/js/jquery-latest.js"></script>
    <!-- <script src="/js/jquery-latest.js"></script> -->
    <script src="/js/jquery.form.js"></script>
    <!-- Custom-UI -->
    <link href="/custom-ui/custom-ui.css" media="screen" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="/custom-ui/custom-ui.js"></script>
    <!-- FormStyler -->
    <script src="/form-styler/jquery.formstyler.js?v=1_4_1"></script>
    <link href="/form-styler/jquery.formstyler.css?v=1_4_1" media="screen" rel="stylesheet" type="text/css" />
    <!-- Bootstrap -->
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.css">
    <script src="/bootstrap/js/bootstrap.js"></script>
    <!-- jQuery.Template -->
    <script type="text/javascript" src="/js/jquery.tmpl.js"></script>
    <script type="text/javascript" src="/js/jquery.tmplPlus.js"></script>
    <!-- Datepicker -->
    <link href="/datepicker/datepicker.css" media="screen" rel="stylesheet" type="text/css" />
    <script src="/datepicker/bootstrap-datepicker.js"></script>
    <script src="/datepicker/locales/bootstrap-datepicker.ru.js"></script>
    <!-- Paginator -->
    <script src="/paginator/paginator3000.js"></script>
    <link href="/paginator/paginator3000.css" media="screen" rel="stylesheet" type="text/css" />
    <!-- Tooltip -->
    <!--<link rel="stylesheet" href="/tooltip/css/base/jquery.ui.all.css">
    <script src="/tooltip/js/ui/jquery.ui.core.js"></script>
    <script src="/tooltip/js/ui/jquery.ui.widget.js"></script>
    <script src="/tooltip/js/ui/jquery.ui.position.js"></script>
    <script src="/tooltip/js/ui/jquery.ui.tooltip.js"></script>-->
    <!-- Validator -->
    <link href="/validation/css/validationEngine.jquery.css" media="screen" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="/validation/js/jquery.validationEngine.js"></script>
    <script type="text/javascript" src="/validation/js/jquery.validationEngine-ru.js"></script>
    <!-- Style -->
    <link rel="stylesheet" href="/css/style.php?v=10">
    <link rel="stylesheet" href="/css/project.css?v=2">    
    <script>

        $(function() {
            try {
                // вкладки
                $('.nav-tabs a').click(function(e) {
                    e.preventDefault();
                    $(this).tab('show');
                });
                // кастомизация инпутов
                $('input[type=checkbox], input[type=radio], select, input[type=file], input[type=text], input[type=password], input[type=submit], textarea').styler({
                    selectVisibleOptions: 20,
                });
                // выбор даты
                if($.fn.datepicker != undefined) {
                    $('.datepicker').datepicker({
                        format: 'dd-mm-yyyy',
                        language: 'ru',
                        weekStart: 1
                    }).on('changeDate', function(e) {
                       $(this).datepicker('hide');
                    });
                }
                reTooltip();
            } catch(e) {
                alert(e);
            }
        });

        function selectNext(fieldset) {
            if($(fieldset).size() == 0) {
                return false;
            }
            var next_fieldset = $(fieldset).next('fieldset');
            var inputSelector = 'input, select, textarea';
            var control = $(next_fieldset).find(inputSelector).filter(':visible');
            next_control = $(control).not('[type="hidden"]').first();
            if(next_control.size() == 0) {
                selectNext(next_fieldset);
            } else {
                next_control.focus();
            }
            return false;
        }

        function reTooltip() {
            // tooltip
            $('.forms,#inner-table-form-add .popup-form-content').tooltip({
                position: {
                    my: "left+20 center+10",
                    at: "center top",
                    using: function( position, feedback ) {
                        $( this ).css( position );
                        $( "<div>" )
                        .addClass( "arrow" )
                        .addClass( feedback.vertical )
                        .addClass( feedback.horizontal )
                        .appendTo( this );
                    }
                }
            });
        }

        // @author: sciner
        function addMoreFileField(target, name, max_input_count) {
            if(max_input_count > 0) {
                if($(target).find('input[type=file]').size() >= max_input_count) {
                    // Нельзя загружать больше файлов чем записано в Constant::VAR_MAX_UPLOAD_FILES
                    return false;
                }
            }
            var f = '<input name="'+name+'" type="file" class="gn-file-add" data-more_file_field_target="' + target + '" /><br />';
            $(target).append(f);
            $(target).find('input[type=file]:last').change(function(e){
                // alert(target + '\n' + name + '\n' + max_input_count);
                var target = $(this).data('more_file_field_target');
                $(this).unbind('change');
                return addMoreFileField(target, name, max_input_count);
            }).styler();
            return false;
        }

    </script>
    <?//= $this->headLink() ?>
    <?//= $this->headScript() ?>

</head>
<body>

    <table class="main-table">
		<? include dirname(__FILE__) . '/header.phtml' ?>
        <tr>
            <td style="height: 1px;" colspan="2">
            	<table style="width: 100%;">
            		<tr>
            			<td>
			                <nav class="navigation">
			                    <?=Plugin_Menu::draw( 'billing-menu', 'main-menu')?>
			                </nav>
			            </td>
			        </tr>
			    </table>
            </td>
        </tr>
        <tr>
            <?if(!$this->hide_left_menu){?>
                <td class="site-left-box">
                    <?=Plugin_Menu::draw($this->MenuCode ?: Zend_Controller_Front::getInstance()->getRequest()->getModuleName(), 'site-left-menu')?>
					
					<? if($this->calendar) { ?>
					<div class="calendar" style="margin: 2em"></div>
					<p class="text-center" id="dateFilterClear"><a class="btn" href="#">Сбросить фильтр</a></p>
					<? } ?>
					
                </td>
            <?}?>
            <td class="site-middle-box">
                <div class="page-content">
                    <?=ob_get_clean();?>
                </div>
            </td>
        </tr>
        <? include dirname(__FILE__).'/footer.phtml' ?>
    </table>
</body>
</html>